# Generated by Django 3.1.7 on 2021-04-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210412_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPagination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_page', models.IntegerField(default=10)),
                ('category_page', models.IntegerField(default=10)),
                ('tag_page', models.IntegerField(default=10)),
            ],
        ),
    ]
