# Generated by Django 3.1.7 on 2021-04-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_title',
            field=models.CharField(blank=True, help_text='リンク先のページタイトルとは別のリンク名を付けたい時のみ', max_length=50, null=True, verbose_name='Title(Option)'),
        ),
    ]
